#!/usr/bin/env python

"""
Slack incoming webhook
----------------------
There are a few ways to talk to slack, this might be the simplest.

https://api.slack.com/internal-integrations
https://api.slack.com/incoming-webhooks

This is not fast, because a new ssl connection is set up for each line
of standard in.
"""

import json
import requests
import os
import sys
import logging

try:
    if os.environ['DEBUG']:
        logging.basicConfig(level=logging.DEBUG)
except KeyError:
    pass

prefix = os.getenv('PREFIX', '')
suffix = os.getenv('SUFFIX', '')
channel = os.getenv('CHANNEL')

url = os.environ['SLACK_WEBHOOK']

for line in sys.stdin:
    payload = {'text': prefix + line + suffix}
    if channel:
        payload['channel'] = channel
    r = requests.post(url, data=json.dumps(payload))
